### PR TITLE
first push

### PR DESCRIPTION
**Pull request by chchchow**

### CODE REVIEW

**Comment by mmarabell** [comment]
I see that you have loaded in the previous files/code from the last few assignments to prepare for this one and noticed the Pokemon.java is your own. I have tested everything you have here, including your PokemonException file. All of the code you have uploaded is properly working and if you want, you may refer to any of my code if you need to if it helps with starting off somewhere. As of right now, I only have the PokeNode file, but I am currently working on the Tree code.

**Comment by chchchow** [comment]
Thank you, I just finished my PokeNode, and I am currently working on PokeTree, feel free to Check it out.

**Comment by mybad812** [comment]
The codes are great. Pretty sure it will work and satisfied the grading rubric. Well done.
Sorry for the late reply.

**Comment by mmarabell** [comment]
After reviewing your changes and uploads, your code looks good with check style and is following the rubric. I wish you luck on completing your Pokedex.java and getting it to call the methods functionally. Great work!

**Comment by chchchow** [comment]
Thank You! I just posted some changes to my pokedex, I tried running the program but it is running into some error, I am not very sure that I am doing it the proper way.

**Pull request closed without merging**
